### ISSUE TITLE
Suggestion: including changes from nightly Process Hacker

### ISSUE THREAD

**Issue by diversenok** [processhacker/phnt#12]
The definitions in this repository are usually somewhat behind those that are available for Process Hacker.

@dmex wrote:
> PHNT is supposed to be a stable repository. I test/update types with PH first then sync those changes with phnt so they're more or less guaranteed to work properly.

It is a reasonable approach, but it makes it harder for third-party projects to include the latest changes available for Process Hacker. Currently, if someone wants to use the latest definitions that are not yet available here, they have three options:
1. Copy necessary header files from Process Hacker.
2. Fork this repository, merge changes from the Process Hacker's version, and include it as a submodule.
3. Include the entire Process Hacker as a submodule.

Therefore, I have a suggestion.

How about maintaining both stable and nightly versions of phnt here on different branches? This way, those who need well-tested definitions can use the main branch, while Process Hacker and other projects that want to include the latest types can reference commits on the nightly branch.

**Comment by rich-ayr** [comment]
Made a standalone version that automatically pulls the phnt folder from master branch if there were any changes to it every night.
If you are interested in using it you can check it out under https://github.com/oberrich/phnt_nightly

Script used to generate/update the repo: https://gist.github.com/oberrich/d0db45cb71fdbf185ec7c922b6b2b6d6

**Comment by dmex** [comment]
You can always create an issue if there's anything missing or needs updating. I'll look at creating a build script which automatically merges any changes similar to @oberrich's script 👍
