### ISSUE TITLE
Updates & submodule of processhacker repo

### ISSUE THREAD

**Issue by wbenny** [processhacker/phnt#2]
Hi!
Placing these headers into a standalone repo was a nice step, and I personally waited for it for a long time. Anyway, I see that processhacker repository have own copy of these headers - plus, unlike this repo, they're beeing updated there.

Are there any plans to keep headers in this repository up-to-date with headers in processhacker repo, or - maybe even better - to make this repo as a git submodule in the processhacker's repository?

**Comment by dmex** [comment]
> Are there any plans to keep headers in this repository up-to-date with headers in processhacker repo

Yes. It's just easier for me to test changes in the other repository (with Process Hacker) before adding them here. 

> make this repo as a git submodule in the processhacker's repository?

Eventually 👍
