### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mrexodia** [processhacker/phnt#27]
It looks like the files [upstream](https://github.com/winsiderss/systeminformer/tree/master/phnt/include) are already licensed under MIT. Would it be possible to change the license here as well to match?

**Comment by Mecanik** [comment]
+1 on this one. Please change the license to MIT.

**Comment by rich-ayr** [comment]
If anyone needs an MIT licensed version, I've just accounted for this change on my [nightly mirror](https://github.com/oberrich/phnt_nightly).

**Comment by mrexodia** [comment]
Yeah, did the same for my single-header version: https://github.com/mrexodia/phnt-single-header
