### ISSUE TITLE
IORing APIs

### ISSUE THREAD

**Issue by kawaii-ghost** [processhacker/phnt#29]
As for Windows 11 22H2, there's new system call for IORing like `NtCreateIoRing` and `NtSubmitIoRing`

https://learn.microsoft.com/en-us/windows/win32/api/ioringapi/nf-ioringapi-createioring
https://learn.microsoft.com/en-us/windows/win32/api/ioringapi/nf-ioringapi-submitioring

**Comment by dmex** [comment]
they're in the upstream repo: https://github.com/winsiderss/systeminformer/blob/5f09f1959b0dccf8cfbbdaa06968b5783ed9318f/phnt/include/ntioapi.h#L1973-L2012
