### ISSUE TITLE
Errors in some heap constants

### ISSUE THREAD

**Issue by zodiacon** [processhacker/phnt#30]
#define RTL_HEAP_UNCOMMITTED_RANGE  (USHORT)0x1000
#define RTL_HEAP_PROTECTED_ENTRY    (USHORT)0x2000
#define RTL_HEAP_LARGE_ALLOC        (USHORT)0x4000
#define RTL_HEAP_LFH_ALLOC          (USHORT)0x8000

**Comment by dmex** [comment]
Fixed upstream 👍 

https://github.com/winsiderss/systeminformer/commit/5a0f8e892e02205a7f56ffe152e8be68bbbaf99b
