### ISSUE TITLE
The vcpkg package version is too low to support Win11

### ISSUE THREAD

**Issue by frendguo** [processhacker/phnt#32]
I installed the latest phnt package through vcpkg, but found that the definition of PHNT_VERSION is only up to PHNT_20H1, see the latest code already support to Win11 22H2, can you update the package of vcpkg?

**Comment by dmex** [comment]
We never added PHNT to vcpkg and didn't even know it was on there until just now 🤔

Anyone can modify/update vcpkg by forking their repository: 
https://github.com/microsoft/vcpkg

Update the files for PHNT:
https://github.com/search?q=repo%3Amicrosoft%2Fvcpkg%20phnt&type=code

Then submit a PR back to their repository and it'll update when the automated checks complete.

**Comment by frendguo** [comment]
Okay, got it.

I'll go update it.

Thank you for your reply.

**Comment by dmex** [comment]
@frendguo 

The PR failed because the format of vcpkg.json changed. 

You can copy the newer format from the other files:
https://github.com/microsoft/vcpkg/blob/master/ports/7zip/vcpkg.json
https://github.com/microsoft/vcpkg/blob/master/ports/alac/vcpkg.json

**Comment by frendguo** [comment]
@dmex Thank you for your help. I have updated the file as you suggested.
