### ISSUE TITLE
Build issue with newest SDK/WDK (redefinition of structures)

### ISSUE THREAD

**Issue by SinaKarvandi** [processhacker/phnt#34]
Hi,
I would like to report an issue regarding the compilation of HyperDbg against the newest SDK/WDK.

It seems that the new SDK has the definition of `_FILE_STAT_LX_INFORMATION` and other functions mentioned here:
![image](https://github.com/winsiderss/phnt/assets/13383992/cef01387-e6d9-410e-af97-25ad0fb90399)

Since we use **phnt** as a submodule to HyperDbg, we'll encounter building issues that seem to be related to the redefinition of the above functions. We could fix it by commenting the above structures in our fork of phnt but in this case, you might also be needed to either remove or comment those structures if needed.

Thanks a lot for maintaining this great project.

**Comment by dmex** [comment]
I've updated the types with these and other changes from upstream 👍

**Comment by SinaKarvandi** [comment]
Thanks
