### ISSUE TITLE
struct redefinitions

### ISSUE THREAD

**Issue by sklaw** [processhacker/phnt#45]
![image](https://github.com/user-attachments/assets/ab7edddc-2df1-4466-9910-4c0a632d38cc)

**Comment by sklaw** [comment]
Win SDK version: 10.0.26100.0

**Comment by sklaw** [comment]
phnt installed from https://vcpkg.link/ports/phnt/v/2024-05-22/0

**Comment by rich-ayr** [comment]
This issue was fixed upstream in https://github.com/winsiderss/systeminformer/commit/060790a298177dea9cdc99663821bfea17de9c5b but the vcpkg release hasn't been updated to reflect this change yet.
